### ISSUE TITLE
Parallel compose only works sequentially

### ISSUE THREAD

**Issue by ptigwe** [gtn-org/gtn#12]
I tried to implement a simple `parallelFor` using the underlying threadpool.
```cpp
template <typename FuncType>
auto parallelFor(FuncType&& function, size_t size) {
  // Skipping bits similar to parallelMap
  ...
  for (size_t i = 0; i < size; ++i) {
    futures[i] = threadPool.get().enqueue(
      [size, i, &function, &eMutex, &eQueue]() -> OutType {
        try {
          return function(i);
        } catch (...) {
          .....
        }
      }
    );
  }
  ....
  }
  return out.value();
}
```

When using this method to perform the various for loops which according to the comments, should be independent on the iteration, I found that the code tends to fail. So far, my guess as to the source of the error is in the `computeNodeAndArcPair` function, although not sure.

An easy way to reproduce this error is to reverse the order in which the arcs are being processed. For instance on [line 668](https://github.com/gtn-org/gtn/blob/7b002cc05b3f0ae85c313da05803b0392b97f5fe/gtn/experimental/parallel_compose.cpp#L668)
```cpp
    for (int tid = totalArcs - 1; tid > 0; --tid) {
```

Again the same on [line 491](https://github.com/gtn-org/gtn/blob/7b002cc05b3f0ae85c313da05803b0392b97f5fe/gtn/experimental/parallel_compose.cpp#L491) and [line 372](https://github.com/gtn-org/gtn/blob/7b002cc05b3f0ae85c313da05803b0392b97f5fe/gtn/experimental/parallel_compose.cpp#L372)

**Comment by awni** [comment]
Were you running this on the GPU or the CPU? E.g. which compose function are you calling? Can you share the full code you ran?

**Comment by ptigwe** [comment]
The test in question is being run on the CPU, I haven't run this on the GPU to check. 

There are two ways to reproduce the error, both of which are available on the following gist as patches 
https://gist.github.com/ptigwe/d066f45df728c9326df74b51db17c030

And for each one of the two patches, running `make build && ./test/parallel_compose_test` is sufficient to reproduce the error.

**Comment by awni** [comment]
I would recommend using the sequential compose and threading at the level of the full graph if you are doing CPU composition. This should work out of the box with our [parallelMap](https://gtn.readthedocs.io/en/latest/parallel.html). 

Our CPU parallel compose is not well optimized or well tested as we have been prioritizing the CUDA implementation.
