### ISSUE TITLE
Compilation error with CUDA

### ISSUE THREAD

**Issue by alumae** [gtn-org/gtn#31]
I am trying to compile GTN with CUDA support.
I am using CUDA 11.2 and gcc 9.4.0.

I ran:
`cmake -DCMAKE_CUDA_COMPILER=/usr/local/cuda/11.2/bin/nvcc  -DCMAKE_CUDA_ARCHITECTURES=80 ..` which succeeds.

However, `cmake -j 8` results in:

    $ make -j 8

    Scanning dependencies of target gtn
    [  5%] Building CXX object CMakeFiles/gtn.dir/gtn/creations.cpp.o
    [  6%] Building CXX object CMakeFiles/gtn.dir/gtn/device.cpp.o
    [ 11%] Building CXX object CMakeFiles/gtn.dir/gtn/cpu/shortest.cpp.o
    [  3%] Building CXX object CMakeFiles/gtn.dir/gtn/cpu/creations.cpp.o
    [ 13%] Building CXX object CMakeFiles/gtn.dir/gtn/cpu/compose.cpp.o
    [ 13%] Building CXX object CMakeFiles/gtn.dir/gtn/cpu/functions.cpp.o
    [ 13%] Building CXX object CMakeFiles/gtn.dir/gtn/autograd.cpp.o
    [ 13%] Building CXX object CMakeFiles/gtn.dir/gtn/criterions.cpp.o
    [ 15%] Building CXX object CMakeFiles/gtn.dir/gtn/functions.cpp.o
    [ 16%] Building CXX object CMakeFiles/gtn.dir/gtn/graph.cpp.o
    [ 18%] Building CXX object CMakeFiles/gtn.dir/gtn/parallel/parallel_map.cpp.o
    [ 20%] Building CXX object CMakeFiles/gtn.dir/gtn/rand.cpp.o
    [ 22%] Building CXX object CMakeFiles/gtn.dir/gtn/utils.cpp.o
    [ 23%] Building CUDA object CMakeFiles/gtn.dir/gtn/cuda/creations.cu.o
    [ 25%] Building CUDA object CMakeFiles/gtn.dir/gtn/cuda/compose.cu.o
    [ 27%] Building CUDA object CMakeFiles/gtn.dir/gtn/cuda/cuda.cu.o
    [ 28%] Building CXX object CMakeFiles/gtn.dir/gtn/cuda/functions.cpp.o
    [ 30%] Building CUDA object CMakeFiles/gtn.dir/gtn/cuda/shortest.cu.o
    /gpfs/mariana/home/tanel.alumae/tools/gtn/gtn/cuda/shortest.cu(19): error: A __constant__ variable cannot be marked constexpr
    
    /gpfs/mariana/home/tanel.alumae/tools/gtn/gtn/cuda/shortest.cu(20): error: A __constant__ variable cannot be marked constexpr
    
    2 errors detected in the compilation of "/gpfs/mariana/home/tanel.alumae/tools/gtn/gtn/cuda/shortest.cu".
    make[2]: *** [CMakeFiles/gtn.dir/build.make:303: CMakeFiles/gtn.dir/gtn/cuda/shortest.cu.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[1]: *** [CMakeFiles/Makefile2:198: CMakeFiles/gtn.dir/all] Error 2
    make: *** [Makefile:160: all] Error 2

Any ideas?

**Comment by awni** [comment]
Sorry for the delay. I removed the `constexpr` from shortest.cu. Could you try reinstalling and let me know if it still doesn't work?

Thanks!
